### ISSUE TITLE
Inline images won't be displayed in the content HTML

### ISSUE THREAD

**Issue by donmerendolo** [L4cache/kemono-dl#13]
### Version

Version: 2022.04.28 (commit 8e64273ee)

### Your Command

```bash

python kemono-dl.py --links https://kemono.party/patreon/user/37159802/post/72681481 --cookies ../cookies.txt --content --inline

```

### Description of bug
Inline images won't be displayed in the content HTML of a post due to an incorrect path.
Take [this post](https://kemono.party/patreon/user/37159802/post/72681481) for example: the path of the first image is `Downloads\patreon\stuffmadehere [37159802]\[20221002] [72681481] Operation tiny box\inline\1_9f3330bd3d47883e403a2d9f9ebea0f7ac189d6414143e8375fa912d50e61504.jpg` which doesn't show it.
Changing it to the relative path `.\inline\1_9f3330bd3d47883e403a2d9f9ebea0f7ac189d6414143e8375fa912d50e61504.jpg` fixes it.

### How To Reproduce
Download a post that has inline images with the `--inline` and `--content` options and open the generated HTML file.

**Comment by donmerendolo** [comment]
I've changed `inline_image['src'] = file['file_path']` for `inline_image['src'] = os.path.join(*re.split(r'\\|/', file['file_path'])[-2:])` in `get_inline_images()`. It works for me but it's not a general fix, as it doesn't take into account the pattern, right?

**Comment by L4cache** [comment]
i'll investigate this.

**Comment by L4cache** [comment]
fixed (probably), please check

**Comment by donmerendolo** [comment]
Working well here. Thank you 😄
