### ISSUE TITLE
DDOS Protect 

### ISSUE THREAD

**Issue by YTOAA** [L4cache/kemono-dl#14]
The recent update of the chemono has added a kind of firewall that prevents DDoS, which has disrupted the download.
The cookie does not change even though it has been updated.

Traceback (most recent call last):
File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono4/src/main.py", line 741, in start_download
self.get_post(url)
File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono4/src/main.py", line 163, in get_post
json = self.session.get(url=f"{api}?o={chunk}", cookies=self.cookies, headers=self.headers, timeout=self.timeout).json()
File "/home/timi/.local/lib/python3.10/site-packages/requests/models.py", line 917, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <title>DDOS-GUARD</title><script>var DOMReady=function(t){var e=document,d="addEventListener";e[d]?ed:window.attachEvent("onload",t)},loadScript=function(t,e){var d=document.createElement("script");d.type="text/javascript",d.src=t,"string"==typeof e&&""!==e&&(d.id=e),(document.getElementsByTagName("head")[0]||document.body).appendChild(d)};DOMReady(function(){loadScript("/.well-known/ddos-guard/check?context=free_splash","ddg_script_f"),loadScript("https://check.ddos-guard.net/check.js")});</script><style>*{margin:0;padding:0}body,html{font-family:Open Sans,Arial,Helvetica,sans-serif;height:100%;color:#333}#wrap-main{-webkit-box-flex:1;-ms-flex:1 0 auto;flex:1 0 auto;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin:0 auto;max-width:1000px;padding:0 10px 70px}#link-ddg{-webkit-box-flex:0;-ms-flex:0 0 auto;flex:0 0 auto;white-space:nowrap;margin:0 auto 30px;font-size:12px;color:#636363}#link-ddg a{text-decoration:none}#link-ddg a:active,#link-ddg a:hover,#link-ddg a:link,#link-ddg a:visited{color:#3399e0}#link-ddg a:focus{color:#3399e0}.container{background:#fff;margin:0 auto}#dg-load{margin-top:25px}.logo-foot{margin-bottom:10px}@media screen and (max-width:1200px){.main{width:500px}#link-ddg{font-size:12px}}@media screen and (max-width:767px){#description{font-size:13px}#link-ddg{margin-bottom:10px;font-size:9px}}.logo{width:120px;margin-bottom:35px}#title{font-size:32px;font-weight:900;margin-bottom:40px}#description{color:#8f9390;margin-bottom:30px}.container{display:-webkit-box;display:-ms-flexbox;display:flex;display:-webkit-flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:100%;text-align:center;background:url(data:image/svg+xml;base64,PHN2ZyBpZD0i0KHQu9C+0LlfMSIgZGF0YS1uYW1lPSLQodC70L7QuSAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjYuNzUgNDcuOTciPjxkZWZzPjxzdHlsZT4uY2xzLTF7ZmlsbDojZmZmO308L3N0eWxlPjwvZGVmcz48dGl0bGU+0JzQvtC90YLQsNC20L3QsNGPINC+0LHQu9Cw0YHRgtGMIDE8L3RpdGxlPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTEzNS41NSwzOS44MmMtLjM4LDAtLjc1LDAtMS4xMywwYTE4LjkxLDE4LjkxLDAsMCwwLTM1LjMzLTQuNTNBMjUuMjYsMjUuMjYsMCwwLDAsNzcuMjEsMjIuN2MtLjgyLDAtMS42MywwLTIuNDMuMTJBMjkuMjYsMjkuMjYsMCwwLDAsMTcsMjkuMjZhMjkuNTksMjkuNTksMCwwLDAsLjE2LDNBMTguNTIsMTguNTIsMCwwLDAsMCw0OEgxNTAuNDNBMTcuNjQsMTcuNjQsMCwwLDAsMTM1LjU1LDM5LjgyWiIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTE1OS40OSw0NS40NUE5LjU4LDkuNTgsMCwwLDAsMTUzLDQ4aDEzQTkuNTgsOS41OCwwLDAsMCwxNTkuNDksNDUuNDVaIi8+PC9zdmc+) center bottom no-repeat}.lds-spin{width:80px;height:80px}@media screen and (max-width:1200px){.logo{width:100px}#title{font-size:29px}}@media screen and (max-width:770px){.logo{width:70px;margin-bottom:10px}#description,#title{font-size:15px;margin-bottom:10px}#description{font-size:13px}.lds-spin{width:40px;height:40px}}</style>

<script type="text/javascript">var lang=navigator.language,host=window.location.hostname;"ru"==lang||"ru-RU"==lang?(document.getElementById("title").innerHTML="Проверка браузера перед переходом на сайт "+host,document.getElementById("description").innerHTML="Это автоматический процесс. Вы будете перенаправлены на запрашиваемый ресурс в ближайшее время.
Пожалуйста ожидайте...",document.getElementById("link").innerHTML="Защита от DDoS-атак DDos-Guard"):(document.getElementById("title").innerHTML="Checking your browser accessing "+host,document.getElementById("description").innerHTML="This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds...",document.getElementById("link").innerHTML="DDoS protection by DDos-Guard");</script>: 0
INFO:Downloading posts from kemono.party.party | fanbox | pepper0 | 10013868
ERROR:Unable to get posts for https://kemono.party/fanbox/user/10013868
Traceback (most recent call last):
File "/home/timi/.local/lib/python3.10/site-packages/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono4/src/main.py", line 741, in start_download
self.get_post(url)
File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono4/src/main.py", line 163, in get_post
json = self.session.get(url=f"{api}?o={chunk}", cookies=self.cookies, headers=self.headers, timeout=self.timeout).json()
File "/home/timi/.local/lib/python3.10/site-packages/requests/models.py", line 917, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <title>DDOS-GUARD</title><script>var DOMReady=function(t){var e=document,d="addEventListener";e[d]?ed:window.attachEvent("onload",t)},loadScript=function(t,e){var d=document.createElement("script");d.type="text/javascript",d.src=t,"string"==typeof e&&""!==e&&(d.id=e),(document.getElementsByTagName("head")[0]||document.body).appendChild(d)};DOMReady(function(){loadScript("/.well-known/ddos-guard/check?context=free_splash","ddg_script_f"),loadScript("https://check.ddos-guard.net/check.js")});</script><style>*{margin:0;padding:0}body,html{font-family:Open Sans,Arial,Helvetica,sans-serif;height:100%;color:#333}#wrap-main{-webkit-box-flex:1;-ms-flex:1 0 auto;flex:1 0 auto;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin:0 auto;max-width:1000px;padding:0 10px 70px}#link-ddg{-webkit-box-flex:0;-ms-flex:0 0 auto;flex:0 0 auto;white-space:nowrap;margin:0 auto 30px;font-size:12px;color:#636363}#link-ddg a{text-decoration:none}#link-ddg a:active,#link-ddg a:hover,#link-ddg a:link,#link-ddg a:visited{color:#3399e0}#link-ddg a:focus{color:#3399e0}.container{background:#fff;margin:0 auto}#dg-load{margin-top:25px}.logo-foot{margin-bottom:10px}@media screen and (max-width:1200px){.main{width:500px}#link-ddg{font-size:12px}}@media screen and (max-width:767px){#description{font-size:13px}#link-ddg{margin-bottom:10px;font-size:9px}}.logo{width:120px;margin-bottom:35px}#title{font-size:32px;font-weight:900;margin-bottom:40px}#description{color:#8f9390;margin-bottom:30px}.container{display:-webkit-box;display:-ms-flexbox;display:flex;display:-webkit-flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;-webkit-box-pack:center;-ms-flex-pack:center;justify-content:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:100%;text-align:center;background:url(data:image/svg+xml;base64,PHN2ZyBpZD0i0KHQu9C+0LlfMSIgZGF0YS1uYW1lPSLQodC70L7QuSAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjYuNzUgNDcuOTciPjxkZWZzPjxzdHlsZT4uY2xzLTF7ZmlsbDojZmZmO308L3N0eWxlPjwvZGVmcz48dGl0bGU+0JzQvtC90YLQsNC20L3QsNGPINC+0LHQu9Cw0YHRgtGMIDE8L3RpdGxlPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTEzNS41NSwzOS44MmMtLjM4LDAtLjc1LDAtMS4xMywwYTE4LjkxLDE4LjkxLDAsMCwwLTM1LjMzLTQuNTNBMjUuMjYsMjUuMjYsMCwwLDAsNzcuMjEsMjIuN2MtLjgyLDAtMS42MywwLTIuNDMuMTJBMjkuMjYsMjkuMjYsMCwwLDAsMTcsMjkuMjZhMjkuNTksMjkuNTksMCwwLDAsLjE2LDNBMTguNTIsMTguNTIsMCwwLDAsMCw0OEgxNTAuNDNBMTcuNjQsMTcuNjQsMCwwLDAsMTM1LjU1LDM5LjgyWiIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTE1OS40OSw0NS40NUE5LjU4LDkuNTgsMCwwLDAsMTUzLDQ4aDEzQTkuNTgsOS41OCwwLDAsMCwxNTkuNDksNDUuNDVaIi8+PC9zdmc+) center bottom no-repeat}.lds-spin{width:80px;height:80px}@media screen and (max-width:1200px){.logo{width:100px}#title{font-size:29px}}@media screen and (max-width:770px){.logo{width:70px;margin-bottom:10px}#description,#title{font-size:15px;margin-bottom:10px}#description{font-size:13px}.lds-spin{width:40px;height:40px}}</style>

<script type="text/javascript">var lang=navigator.language,host=window.location.hostname;"ru"==lang||"ru-RU"==lang?(document.getElementById("title").innerHTML="Проверка браузера перед переходом на сайт "+host,document.getElementById("description").innerHTML="Это автоматический процесс. Вы будете перенаправлены на запрашиваемый ресурс в ближайшее время.
Пожалуйста ожидайте...",document.getElementById("link").innerHTML="Защита от DDoS-атак DDos-Guard"):(document.getElementById("title").innerHTML="Checking your browser accessing "+host,document.getElementById("description").innerHTML="This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds...",document.getElementById("link").innerHTML="DDoS protection by DDos-Guard");</script>: 0

**Comment by L4cache** [comment]
This is really annoying for me as well... I've tried several things to mitigate it but got no progress...
Then seems suddenly it solved itself...
Is it working on your side?

**Comment by YTOAA** [comment]
It's working normally again now. However, I don't know when the symptoms will be repeated again.
