### ISSUE TITLE
API endpoints and responses seem to have changed.

### ISSUE THREAD

**Issue by gel-friend** [L4cache/kemono-dl#19]
According to [schema](https://kemono.party/api/schema), the endpoint needs `v1` prefix.
In addition, the datetime format in responses seems to be iso8601 format, so we have to use `fromisoformat` in [this line](https://github.com/L4cache/kemono-dl/blob/4b1a56e6123905d7dac0fa7be160b8c2c0fbdf97/src/main.py#L833) (and remove second argument).

**Comment by L4cache** [comment]
thanks
