### ISSUE TITLE
Datebefore Dateafter time format change

### ISSUE THREAD

**Issue by anon567321** [L4cache/kemono-dl#23]
in args.py you need to change this line

Current 306 args[key] = datetime.datetime.strptime(args[key], r'%Y%m%d')
New      306 args[key] = datetime.datetime.fromisoformat(args[key])

The date format in datebefore/dateafter functions should now be YYYY-MM-DD, not YYYYMMDD.

**Comment by L4cache** [comment]
This is the format for parsing args, not related to the api returned value change.

**Comment by L4cache** [comment]
Please provide more info if you actually encountered problem.

**Comment by anon567321** [comment]
When I used the function "--user-updated-dateafter 20231021", I got the error "20231021 is an invalid date | correct format: YYYYMMDD".
But after replacing line 306, and using the function "--user-updated-dateafter 2023-10-21", everything works properly

**Comment by L4cache** [comment]
> When I used the function "--user-updated-dateafter 20231021", I got the error "20231021 is an invalid date | correct format: YYYYMMDD". But after replacing line 306, and using the function "--user-updated-dateafter 2023-10-21", everything works properly

Can't reproduce.

**Comment by SamsonTKG** [comment]
When I use "--dateafter" I get the following error.

ERROR:Unable to get posts for URL
Traceback (most recent call last):
  File "C:\Programs\kemono-dl\src\main.py", line 834, in start_download
    self.get_post(url)
  File "C:\Programs\kemono-dl\src\main.py", line 201, in get_post
    if self.skip_post(post,False):
  File "C:\Programs\kemono-dl\src\main.py", line 672, in skip_post
    elif check_date(self.get_date_by_type(post['post_variables']['published' if not self.fp_added else 'added']), self.date, self.datebefore, self.dateafter):
  File "C:\Programs\kemono-dl\src\main.py", line 843, in get_date_by_type
    t = datetime.datetime.fromisoformat(time)
ValueError: Invalid isoformat string: '20230926'

Could you please help me?

**Comment by anon567321** [comment]
try "--dateafter 2023-09-26"

**Comment by L4cache** [comment]
I really can't reproduce unless you provide specific links.

**Comment by recoil2293** [comment]
Hello, I'm having the same issue.

INFO:Downloading posts from kemono.su | patreon | Spageta | 68982275
ERROR:Unable to get posts for https://kemono.su/patreon/user/68982275
Traceback (most recent call last):
  File "/media/user/Garden/kemono-dl-main/src/main.py", line 834, in start_download
    self.get_post(url)
  File "/media/user/Garden/kemono-dl-main/src/main.py", line 201, in get_post
    if self.skip_post(post,False):
  File "/media/user/Garden/kemono-dl-main/src/main.py", line 672, in skip_post
    elif check_date(self.get_date_by_type(post['post_variables']['published' if not self.fp_added else 'added']), self.date, self.datebefore, self.dateafter):
  File "/media/user/Garden/kemono-dl-main/src/main.py", line 843, in get_date_by_type
    t = datetime.datetime.fromisoformat(time)
ValueError: Invalid isoformat string: '20231013'

Thank you for your help!

**Comment by L4cache** [comment]
> Hello, I'm having the same issue.
> 
> INFO:Downloading posts from kemono.su | patreon | Spageta | 68982275 ERROR:Unable to get posts for https://kemono.su/patreon/user/68982275 Traceback (most recent call last): File "/media/user/Garden/kemono-dl-main/src/main.py", line 834, in start_download self.get_post(url) File "/media/user/Garden/kemono-dl-main/src/main.py", line 201, in get_post if self.skip_post(post,False): File "/media/user/Garden/kemono-dl-main/src/main.py", line 672, in skip_post elif check_date(self.get_date_by_type(post['post_variables']['published' if not self.fp_added else 'added']), self.date, self.datebefore, self.dateafter): File "/media/user/Garden/kemono-dl-main/src/main.py", line 843, in get_date_by_type t = datetime.datetime.fromisoformat(time) ValueError: Invalid isoformat string: '20231013'
> 
> Thank you for your help!

Have you tried latest changes?

**Comment by recoil2293** [comment]
Thank you!

**Comment by SamsonTKG** [comment]
Worked, too. Thank you!

**Comment by L4cache** [comment]
The issue of OP is different from the addressed issue above, I guess. Please provide more info.

**Comment by anon567321** [comment]
I've already fixed it myself. Actually, I'm using this fork: https://github.com/ovear/kemono-dl
As I understand it, it is no longer active, and your fork is the most actual one now.
Since the part of the code responsible for the date was the same in his and yours code, I thought that your fork would have the same problem.
