### ISSUE TITLE
The new domain will be applied.

### ISSUE THREAD

**Issue by YTOAA** [L4cache/kemono-dl#24]
C:\Users\wf\Documents\kemono-dl-main>python kemono-dl.py --cookies "cookie.txt" --links https://kemono.su/patreon/user/90200210/post/91250001
WARNING:URL is not downloadable | https://kemono.su/patreon/user/90200210/post/91250001
ERROR:No creator information was retrieved. | exiting

You no longer use .party.
I think it works well even if I simply change all the party to su...?

[kemono-dl-main - Cp.zip](https://github.com/L4cache/kemono-dl/files/13062369/kemono-dl-main.-.Cp.zip)

The attachment is simply a change of party to su.

**Comment by L4cache** [comment]
I'll just plagiarize from ovear🧐

**Comment by L4cache** [comment]
I think I still need to deal with archived links tough.

**Comment by L4cache** [comment]
Should be OK now.
