### ISSUE TITLE
Error: Unable to to get favorite posts from kemono.su

### ISSUE THREAD

**Issue by slormo** [L4cache/kemono-dl#26]
### Version

Version: 2022.04.28 (latest github pull as 11/11/23)

### Your Command

```bash

python3 kemono-dl.py --cookies "kemono.party_cookies.txt" --kemono-fav-posts --content --dirname-pattern "Downloads2" --filename-pattern "[{published}] - {username} ({service}_{user_id}) - {title} ({id}) {index}_{filename}.{ext}" --other-filename-pattern "[{published}] - {username} ({service}_{user_id}) - {title} ({id}).{ext}" --verbose

```

### Description of bug

Gives the error "Unable to to get favorite posts from kemono.su"

### How To Reproduce

Run command with cookie file

### Error messages and tracebacks

```python

DEBUG:Getting creator json from https://kemono.su/api/v1/creators/
ERROR:Unable to get favorite posts from kemono.su
Traceback (most recent call last):
  File "D:\Nothing in particular\kemono\src\main.py", line 813, in start_download
    self.get_favorites(self.cookie_domains['kemono'], 'post', retry=self.retry)
TypeError: get_favorites() got an unexpected keyword argument 'retry'

```

**Comment by L4cache** [comment]
Please try with the latest change

**Comment by AsiaIceorb** [comment]
I tried the latest version but failed.

ERROR:Unable to get favorite users from kemono.su
Traceback (most recent call last):
  File "G:\kemono-dl-main\src\main.py", line 827, in start_download
    self.get_favorites(self.cookie_domains['kemono'], 'artist', self.k_fav_users)
  File "G:\kemono-dl-main\src\main.py", line 147, in get_favorites
    if not (favorite['service'] in services or 'all' in services):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by L4cache** [comment]
> I tried the latest version but failed.
> 
> ERROR:Unable to get favorite users from kemono.su Traceback (most recent call last): File "G:\kemono-dl-main\src\main.py", line 827, in start_download self.get_favorites(self.cookie_domains['kemono'], 'artist', self.k_fav_users) File "G:\kemono-dl-main\src\main.py", line 147, in get_favorites if not (favorite['service'] in services or 'all' in services): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable

Different issue.
Did you provide argument value to --kemono-fav-users?

**Comment by AsiaIceorb** [comment]
> > I tried the latest version but failed.
> > ERROR:Unable to get favorite users from kemono.su Traceback (most recent call last): File "G:\kemono-dl-main\src\main.py", line 827, in start_download self.get_favorites(self.cookie_domains['kemono'], 'artist', self.k_fav_users) File "G:\kemono-dl-main\src\main.py", line 147, in get_favorites if not (favorite['service'] in services or 'all' in services): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable
> 
> Different issue. Did you provide argument value to --kemono-fav-users?

My command is:
python kemono-dl.py --cookies cookie.txt --kemono-fav-users fanbox --extract-links
It works before.

**Comment by L4cache** [comment]
> > > I tried the latest version but failed.
> > > ERROR:Unable to get favorite users from kemono.su Traceback (most recent call last): File "G:\kemono-dl-main\src\main.py", line 827, in start_download self.get_favorites(self.cookie_domains['kemono'], 'artist', self.k_fav_users) File "G:\kemono-dl-main\src\main.py", line 147, in get_favorites if not (favorite['service'] in services or 'all' in services): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable
> > 
> > 
> > Different issue. Did you provide argument value to --kemono-fav-users?
> 
> My command is: python kemono-dl.py --cookies cookie.txt --kemono-fav-users fanbox --extract-links It works before.

My bad. Should be fixed now.

**Comment by AsiaIceorb** [comment]
> > > > I tried the latest version but failed.
> > > > ERROR:Unable to get favorite users from kemono.su Traceback (most recent call last): File "G:\kemono-dl-main\src\main.py", line 827, in start_download self.get_favorites(self.cookie_domains['kemono'], 'artist', self.k_fav_users) File "G:\kemono-dl-main\src\main.py", line 147, in get_favorites if not (favorite['service'] in services or 'all' in services): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable
> > > 
> > > 
> > > Different issue. Did you provide argument value to --kemono-fav-users?
> > 
> > 
> > My command is: python kemono-dl.py --cookies cookie.txt --kemono-fav-users fanbox --extract-links It works before.
> 
> My bad. Should be fixed now.

Thanks alot.Looking forward to your updates!
