### ISSUE TITLE
About error 429

### ISSUE THREAD

**Issue by anon567321** [L4cache/kemono-dl#30]
Hello, is it possible to reduce the frequency of error 429?
For example, add a delay of half a second before loading the next chunk from api?
I have over 300 artists in favorites, and now the "--user-updated-dateafter" function can run for hours because of the delay.

**Comment by L4cache** [comment]
Probably not.
The server wants you to relax a bit, it's better to do that.

**Comment by anon567321** [comment]
I mean, maybe if you don't access the api so quickly, the error rate will be lower?
When all posts on a page are downloaded, a lot of api requests are made in a very short period of time, followed by a 120-second cooldown.
Maybe we should add a small delay between requests, then the 120-second cooldown will not occur so often?

**Comment by L4cache** [comment]
That's possible...

**Comment by L4cache** [comment]
I guess ovear have dont it.
