### ISSUE TITLE
Output specific gumroad user 429 code

### ISSUE THREAD

**Issue by ytoaa** [L4cache/kemono-dl#32]
DEBUG:Getting creator json from https://kemono.su/api/v1/creators.txt
INFO:Downloading posts from kemono.su | gumroad | E-onsang | 1533812988563
DEBUG:Requesting user json from: https://kemono.su/api/v1/gumroad/user/1533812988563?o=0
WARNING:Failed to get icon, banner, dms, fancards or announcements | Probably 429 | Sleeping for 120 seconds

{'id': 'nzykl', 'user': '1533812988563', 'service': 'gumroad', 'title': 'December 2023 ★★★', 'content': '<p>Including Uncensored, High-res images of...</p><p><br></p><p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.pixiv.net/artworks/114506219">https://www.pixiv.net/artworks/114506219</a></p><p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.pixiv.net/artworks/114537800">https://www.pixiv.net/artworks/114537800</a></p><p><a target="_blank" rel="noopener noreferrer nofollow" href="https://www.pixiv.net/artworks/114663297">https://www.pixiv.net/artworks/114663297</a></p><div id="purchase_text_blocks"><div class="fileEmbed"><a href="/68/de/68deb0fbd237f78a04285b69629c5262cb5318fa3171e661bc2bd86b5bdfc9ec.zip?f=2023.12.4d.zip">2023.12.4d.zip</a></div><p><br></p></div>', 'embed': {}, 'shared_file': False, 'added': '2024-03-17T20:39:48.988893', 'published': '2024-03-09T07:50:42', 'edited': '2024-03-09T07:50:42', 'file': {'covers': [{}], 'thumbnail': {}}, 'attachments': [{'name': '2023.12.4d.zip', 'path': '/68/de/68deb0fbd237f78a04285b69629c5262cb5318fa3171e661bc2bd86b5bdfc9ec.zip'}], 'poll': None, 'captions': None, 'tags': None}
[{'covers': [{}], 'thumbnail': {}}, {'name': '2023.12.4d.zip', 'path': '/68/de/68deb0fbd237f78a04285b69629c5262cb5318fa3171e661bc2bd86b5bdfc9ec.zip'}]

{'id': 'sfezn', 'user': '4607641682653', 'service': 'gumroad', 'title': '[36th] 2022 Monster Hunter Rise Images ', 'content': '<p>Images of Monster Hunter Rise characters</p><p>Images are full size PNG file.</p><p>Hinoe, Minoto 1                          : 2 variation (Normal, Bestiality Bukkake)</p><p>Hinoe, Minoto 2                         : 9 variation (Bestiality) </p><p>Hinoe, Minoto 3 (R-18 ver)      : 13 variation (Bestiality/ Pregnant)</p><p>Hinoe, Minoto 3 (R18-G ver)  : 16 variation (Bestiality/ Pregnant / Birthing)</p><p>Hinoe, Minoto 4                         : 3 variation (Nude, Pregnant, Milk)</p><p>27 ~ 30 Total Images.</p><p><br></p><p>This image pack contains R-18G(Birthing dog) images, So I separate them to R-18G folder. Please be careful when you purchase it.</p><div id="purchase_text_blocks"><div class="fileEmbed"><a href="/7c/2c/7c2cb9f49d56491a2a66400f7c2ca86ea47c25428b25a4ab8aee511a25a24a26.7z?f=2022%20October%20LUNCH.7z">2022 October LUNCH.7z</a></div><div class="fileEmbed"><a href="/8e/e9/8ee915909c62ee52a895c663b3fe43990e2e6d580ebd23bb19fbb290887c90ca.zip?f=2022%20October%20LUNCH.zip">2022 October LUNCH.zip</a></div><p><br></p></div>', 'embed': {}, 'shared_file': False, 'added': '2024-03-29T14:52:26.273195', 'published': '2024-03-20T10:09:14', 'edited': '2024-03-20T10:09:14', 'file': {'name': '2022 October image pack.png', 'path': '/6d/e7/6de7a6e2e1689ccbd8f6bce51d70d41c452c253c4d74aff90ba0d33bfe01ec7e.png', 'covers': [{'original': {'name': '2022 October image pack.png', 'path': '/6d/e7/6de7a6e2e1689ccbd8f6bce51d70d41c452c253c4d74aff90ba0d33bfe01ec7e.png'}, 'main_cover': True}], 'thumbnail': {}}, 'attachments': [{'name': '2022 October LUNCH.7z', 'path': '/7c/2c/7c2cb9f49d56491a2a66400f7c2ca86ea47c25428b25a4ab8aee511a25a24a26.7z'}, {'name': '2022 October LUNCH.zip', 'path': '/8e/e9/8ee915909c62ee52a895c663b3fe43990e2e6d580ebd23bb19fbb290887c90ca.zip'}], 'poll': None, 'captions': None, 'tags': None}
[{'name': '2022 October image pack.png', 'path': '/6d/e7/6de7a6e2e1689ccbd8f6bce51d70d41c452c253c4d74aff90ba0d33bfe01ec7e.png', 'covers': [{'original': {'name': '2022 October image pack.png', 'path': '/6d/e7/6de7a6e2e1689ccbd8f6bce51d70d41c452c253c4d74aff90ba0d33bfe01ec7e.png'}, 'main_cover': True}], 'thumbnail': {}}, {'name': '2022 October LUNCH.7z', 'path': '/7c/2c/7c2cb9f49d56491a2a66400f7c2ca86ea47c25428b25a4ab8aee511a25a24a26.7z'}, {'name': '2022 October LUNCH.zip', 'path': '/8e/e9/8ee915909c62ee52a895c663b3fe43990e2e6d580ebd23bb19fbb290887c90ca.zip'}]

I checked that the name key is not visible in the api compared to other gum rods.
First of all, I temporarily modified the main part as follows.
                try:
                    filename, file_extension = os.path.splitext(attachment['name'])
                except KeyError:
                    continue

**Comment by L4cache** [comment]
That's not 429 though, around the time there were so many 429 so I was just lazy and went "f*** it just assume it's 429"
