### ISSUE TITLE
Support for zip/rar file password scraping

### ISSUE THREAD

**Issue by DABnoREGRET** [L4cache/kemono-dl#33]
Kemono now show the password of archived file. Can you scrape that information to a text file as well?

Example here (NSFW): https://kemono.su/posts/archives/dca4f797d6988b4d2119bed969a0d8616001c6002f34ada94d2ca22b221ad765
![image](https://github.com/L4cache/kemono-dl/assets/57186199/85db9292-6560-4c05-a04a-064722c726a1)

**Comment by L4cache** [comment]
please check

**Comment by DABnoREGRET** [comment]
Works perfectly! Thank you
