### ISSUE TITLE
Duplicate Files

### ISSUE THREAD

**Issue by PerseusRex** [L4cache/kemono-dl#34]
So I recently uninstalled all python versions on my PC and reinstalled Python 3.9. But now when I use this, it'll skip some files because it's hash already exists and others it'll just redownload everything with a different string of letters and numbers from the one that already exists.

**Comment by L4cache** [comment]
Please elaborate.

**Comment by PerseusRex** [comment]
Sorry, I figured it out. I was using one of your old commits, which didn't have --dupe-check, I believe it had --check-local-hash instead. I replaced it with your most recent one and --dupe-check was one of the options. Oh just in case anyways an example of what it was, say one of the pictures was named `02_4054dc5b-1dd4-45bf-ac1e-ef21e3f9c7c6.png` it would still download another one named `02_ZsNEG7jOyvosmGFWq0fryPE2.png`.

**Comment by L4cache** [comment]
OK, closing now, if issue persists feel free to re-open.
