### ISSUE TITLE
a letter except for English

### ISSUE THREAD

**Issue by ytoaa** [L4cache/kemono-dl#36]
python kemono-dl.py --cookies "Q:/kemono/cookie.txt" --dirname-pattern "Q:/kemono/test/{service}/{username}@{user_id}" --links "https://kemono.su/patreon/user/45939644/post/116620363"  --skip-filetypes "clip" --other-filename-pattern "({id}!!{filename}).{ext}"  --filename-pattern "{username}@{user_id} Vol{added} ({index}!!{filename}).{ext}" --inline --inline-filename-pattern "{username}@{user_id} Vol{added} (inline{index}!!{filename}).{ext}" --content --comments --json --extract-links --no-dupe-check --dateafter "20230101"

I wrote the command in this way.

![image](https://github.com/user-attachments/assets/70f898d7-4e5b-4835-8596-5c0f9161f0a1)
Here's a list of a few writers you can test.
https://kemono.su/fanbox/user/3316400
https://kemono.su/fanbox/user/11229342
https://kemono.su/fanbox/user/3316400

However, English is excluded from the user name part
There was a character breaking phenomenon for Korean, Chinese, and Japanese.
We need to make sure that this affects not just the artist's name, but also other things.
For example, there is a file name.

**Comment by L4cache** [comment]
should be fixed now

**Comment by L4cache** [comment]
close now, if there's more problem you can reopen
