### ISSUE TITLE
KeyError: 'name'

### ISSUE THREAD

**Issue by kumasannageru** [L4cache/kemono-dl#37]
### Version

Version: 2024.02.02

### Your Command

```bash

py kemono-dl.py --cookies "cookies.txt" --dirname-pattern "favorite\{username}\[{published}]{title}" --filename-pattern "{index}.{ext}" --kemono-fav-post

```

### Description of bug

I can download most of the posts, but I get errors with some of the posts that I have registered as favorites. I also tried individual downloads by url, but the same error was confirmed.

### How To Reproduce

Once you have added any of these posts to your favorites, run the above command.

Error confirmed post ↓ 
fanbox/user/10083812/post/5336998
fanbox/user/1012802/post/2283971
fanbox/user/1012802/post/2416772
fanbox/user/10751/post/3189616
fanbox/user/163246/post/4672587

### Error messages and tracebacks

```python

INFO:Downloading posts from kemono.su | fanbox | samidareuraniwa | 10083812
ERROR:Unable to get favorite posts from kemono.su
Traceback (most recent call last):
  File "D:\💛\kemono\src\main.py", line 1000, in start_download
    self.get_favorites(self.cookie_domains['kemono'], 'post', retry=self.retry)
  File "D:\💛\kemono\src\main.py", line 167, in get_favorites
    self.get_post(f"https://{domain}/{favorite['service']}/user/{favorite['user']}/post/{favorite['id']}", retry=self.retry)
  File "D:\💛\kemono\src\main.py", line 245, in get_post
    post_tmp = self.clean_post(post, user, site)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\💛\kemono\src\main.py", line 508, in clean_post
    'url': f"https://{domain}/data{attachment['path']}?f={attachment['name']}",
                                                          ~~~~~~~~~~^^^^^^^^
KeyError: 'name'

```

### Additional comments

Please let me know if you need any other information. I hope the bug is resolved.

**Comment by L4cache** [comment]
uh it auto closed when I push the commit
feel free to reopen if anything still wrong
