### ISSUE TITLE
Duplicate file check

### ISSUE THREAD

**Issue by slormo** [L4cache/kemono-dl#8]
### Description

Kemono-DL sometimes duplicates attachments if any were previously downloaded. I think this is because the files change data servers and therefore get given a different name. A hash check might fix this but I'm not sure.

**Comment by L4cache** [comment]
I've noticed that too, but I gonna run dupe file scan for my drives occasionally, so I didn't look into that.
Now I tried to fix it for us, hope it works well.

**Comment by slormo** [comment]
The commit seems to detect dupes well, but now it runs really slow. Making it an optional setting might be a good idea

**Comment by L4cache** [comment]
> The commit seems to detect dupes well, but now it runs really slow. Making it an optional setting might be a good idea

Just to say that the hash compare only takes place when there's files with similar filename, other wise there's just some filename compare, shouldn't be a huge slow down, there may be some other problems.
